[package]
name = "omelette"
version = "0.1.0"
edition = "2021"

[dependencies]
timely = "0.12.0"
differential-dataflow = "0.12.0"
rand = "0.4"
sexp = "1.1.4"
abomonation = "0.7.3"
abomonation_derive = "0.5.0"
